name: cocotest
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: WDA <engineer13@outlook.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

#dependencies:
#  path: ^1.6.0
dependencies:
  uuid: 2.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
